apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coffeeshop-role
  #namespace: 'DEFINE BY WHERE IT IS RUN OR ENTER IT HERE'
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]