apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coffeeshop-role-binding
  #namespace: 'DEFINE BY WHERE IT IS RUN OR ENTER IT HERE'
subjects:
  - kind: ServiceAccount
    name: default
    #namespace: 'DEFINE BY WHERE IT IS RUN OR ENTER IT HERE'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coffeeshop-role